export const content = [
  "You're muted",
  "Sorry, you go ahead",
  "Ceiling shot",
  "Make sense",
  "We lost them",
  "(Awkward Silence)",
  "Clap reaction",
  "Let's get started",
  "Hello Hello?",
  "Can you hear me?",
  "Can we take this offline?",
  "Still loading?",
  "Are we supposed to see smth here?",
  "Can everyone see my screen?",
  "Painful echo",
  "Sorry about that",
  "You are still sharing",
  "Next slide, please",
  "Who just joined?",
  "Can everyone go on mute?",
  "No, still loading",
  "I'll get back to you",
  "Can't hear you",
  "Someone walks through the room in the background of someone's screen",
];
